[package]
name = "zcash-ffi"
version = "0.0.1"
edition = "2021"
description = "Zcash oriented for use by Dart."
repository = "https://github.com/ManyMath/keepass-rust"
license = "MIT"

[lib]
name = "zcash_ffi"
path = "src/lib.rs"
crate-type = ["cdylib", "staticlib"]

[dependencies]
